<?php
session_start();
require"inc/lib.inc.php";
if(isset($_GET["num"])){
	if(isset($_SESSION['name'])){
		if($_SESSION['role']=="admin"){
			$num=$_GET['num'];
			del_art($connect,$num);
			header("Location:index.php");
			exit();
		}
	}
}
else
	header("Location:{$_SERVER['HTTP_REFERER']}");
?>